---
# file: roles/prometheus/files/prometheus.yml

global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'fnsn'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets:
        - c1:9100
        - es0:9100
        - es1:9100
  - job_name: 'elasticsearch'
    static_configs:
      - targets:
        - es0:9108
        - es1:9108
  - job_name: 'ingestor'
    static_configs:
      - targets:
        - c1:12345
  - job_name: 'mergor'
    static_configs:
      - targets:
        - c1:12346
  - job_name: 'cloudwatch'
    scrape_interval: 2m
    scrape_timeout:  2m
    static_configs:
      - targets:
        - c1:9106
