{
 "title": "cloudwatch - exporter process",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "cloudwatch_requests_total - Current",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "cloudwatch_requests_total" }
   ]
  },
  {
   "title": "cloudwatch_requests_total - Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "range",
   "targets": [
    { "expr": "cloudwatch_requests_total" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_exporter_scrape_duration_seconds{job=\"cloudwatch\"}",
     "legendFormat": "scrape_duration"
    }
   ]
  },
  {
   "title": "Scrape Error",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_exporter_scrape_error{job=\"cloudwatch\"}",
     "legendFormat": "scrape_error"
    }
   ]
  }
 ]
}