{
 "title": "cloudwatch - elb",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "load_balancer_name",
    "query": "label_values(aws_elb_healthy_host_count_average{job=\"cloudwatch\"}, load_balancer_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_healthy_host_count_average{job=\"cloudwatch\",load_balancer_name=~\"$load_balancer_name\"}",
     "legendFormat": "healthy"
    },
    {
     "expr": "aws_elb_un_healthy_host_count_average{job=\"cloudwatch\",load_balancer_name=~\"$load_balancer_name\"}",
     "legendFormat": "un_healthy"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_request_count_sum{job=\"cloudwatch\",load_balancer_name=~\"$load_balancer_name\"}",
     "legendFormat": "request_count"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elb_latency_average{job=\"cloudwatch\",load_balancer_name=~\"$load_balancer_name\"}",
     "legendFormat": "latency_average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_estimated_albactive_connection_count_sum{job=\"cloudwatch\",load_balancer_name=~\"$load_balancer_name\"}",
     "legendFormat": "active"
    },
    {
     "expr": "aws_elb_estimated_albnew_connection_count_sum{job=\"cloudwatch\",load_balancer_name=~\"$load_balancer_name\"}",
     "legendFormat": "new"
    }
   ]
  }
 ]
}