{
 "title": "cloudwatch - beanstalk - environment",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(aws_elasticbeanstalk_cpuuser_average{job=\"cloudwatch\"}, environment_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU - user",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_cpuuser_average{job=\"cloudwatch\", environment_name=\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "CPU - system",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_cpusystem_average{job=\"cloudwatch\", environment_name=\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "CPU - iowait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_cpuiowait_average{job=\"cloudwatch\", environment_name=\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Requests - 2XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_requests2xx_sum{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Requests - 3XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_requests3xx_sum{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Requests - 4XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_requests4xx_sum{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Requests - 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_requests5xx_sum{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Requests - Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_requests_total_sum{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Latency - p10",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_latency_p10_average{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Latency - p50",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_latency_p50_average{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Latency - p90",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_latency_p90_average{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Latency - p99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_latency_p99_average{job=\"cloudwatch\",environment_name=~\"$environment\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  }
 ]
}