{
 "title": "cloudwatch - beanstalk - instance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(aws_elasticbeanstalk_cpuuser_average{job=\"cloudwatch\"}, environment_name)"
   },
   {
    "name": "instance_id",
    "query": "label_values(aws_elasticbeanstalk_cpuuser_average{job=\"cloudwatch\",environment_name=\"$environment\"}, instance_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_cpuiowait_average{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "aws_elasticbeanstalk_cpusystem_average{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "system"
    },
    {
     "expr": "aws_elasticbeanstalk_cpuuser_average{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_requests2xx_sum{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "2XX"
    },
    {
     "expr": "aws_elasticbeanstalk_application_requests3xx_sum{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "3XX"
    },
    {
     "expr": "aws_elasticbeanstalk_application_requests4xx_sum{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "4XX"
    },
    {
     "expr": "aws_elasticbeanstalk_application_requests5xx_sum{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elasticbeanstalk_application_latency_p10_average{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "p10"
    },
    {
     "expr": "aws_elasticbeanstalk_application_latency_p50_average{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "aws_elasticbeanstalk_application_latency_p90_average{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "aws_elasticbeanstalk_application_latency_p99_average{job=\"cloudwatch\",instance_id=~\"$instance_id\"}",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}