{
 "title": "cpu_core",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU-0",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu0\",mode=\"user\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu0\",mode=\"system\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu0\",mode=\"iowait\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu0\",mode=\"softirq\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu1\",mode=\"user\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu1\",mode=\"system\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu1\",mode=\"iowait\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu1\",mode=\"softirq\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu2\",mode=\"user\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu2\",mode=\"system\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu2\",mode=\"iowait\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu2\",mode=\"softirq\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU-3",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu3\",mode=\"user\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu3\",mode=\"system\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu3\",mode=\"iowait\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "irate(node_cpu{job=\"node\",cpu=\"cpu3\",mode=\"softirq\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}