{
 "title": "cpu_mode",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "user",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"user\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "system",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"system\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "iowait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"iowait\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "softirq",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"softirq\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "irq",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"irq\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "nice",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"nice\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "steal",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"steal\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "guest",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu{job=\"node\",mode=\"guest\",instance=~\"$node:$port\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  }
 ]
}