{
 "title": "disk",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_written{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Ops - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Ops - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Time - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_ms{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Time - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_write_time_ms{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Merged - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Merged - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_merged{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}