{
 "title": "ingestor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "ingestor_process_uptime" }
   ]
  },
  {
   "title": "cpu time - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "ingestor_process_cpu_total{job=\"ingestor\",type=\"user\"}"
    }
   ]
  },
  {
   "title": "cpu time - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "ingestor_process_cpu_total{job=\"ingestor\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "files_processed_total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "ingestor_files_processed_total{job=\"ingestor\"}"
    }
   ]
  },
  {
   "title": "bulk_es - time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "ingestor_bulk_es_ms_total{job=\"ingestor\"}"
    }
   ]
  },
  {
   "title": "logs_queue_length",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "ingestor_logs_queue_length{job=\"ingestor\"}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ingestor_process_memory{job=\"ingestor\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "cpu time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "ingestor_process_cpu{job=\"ingestor\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "files_processed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ingestor_files_processed_total{job=\"ingestor\"}[20s])",
     "legendFormat": "files_processed"
    }
   ]
  },
  {
   "title": "bulk_es",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(ingestor_bulk_es_ms_total{job=\"ingestor\"}[20s])",
     "legendFormat": "bulk_es_ms_total"
    }
   ]
  },
  {
   "title": "bulk_queue_length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ingestor_logs_queue_length", "legendFormat": "logs_queue_length" }
   ]
  }
 ]
}