{
 "title": "memory",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemFree{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapCached{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SwapFree{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_CommitLimit{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Buffers, Cached, Mapped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Mapped{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Mapped"
    }
   ]
  },
  {
   "title": "Active",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_memory_Active_file{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "file"
    },
    {
     "expr": "node_memory_Active{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_anon{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_memory_Inactive_file{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "file"
    },
    {
     "expr": "node_memory_Inactive{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Page",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonPages{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Pages"
    },
    {
     "expr": "node_memory_AnonHugePages{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "HugePages"
    },
    {
     "expr": "node_memory_PageTables{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_Unevictable{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Unevictable"
    }
   ]
  },
  {
   "title": "Dirty, Writeback",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Dirty"
    },
    {
     "expr": "node_memory_Writeback{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Writeback"
    },
    {
     "expr": "node_memory_WritebackTmp{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "WritebackTmp"
    }
   ]
  },
  {
   "title": "Slab",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SReclaimable{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Reclaim"
    },
    {
     "expr": "node_memory_SUnreclaim{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Unreclaim"
    },
    {
     "expr": "node_memory_Slab{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_KernelStack{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "KernelStack"
    },
    {
     "expr": "node_memory_Mlocked{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Mlocked"
    },
    {
     "expr": "node_memory_Shmem{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Shmem"
    },
    {
     "expr": "node_memory_Bounce{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Bounce"
    },
    {
     "expr": "node_memory_HardwareCorrupted{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "HwCorrupted"
    }
   ]
  }
 ]
}