{
 "title": "mergor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "mergor_process_uptime" }
   ]
  },
  {
   "title": "cpu time - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "mergor_process_cpu_total{job=\"mergor\",type=\"user\"}"
    }
   ]
  },
  {
   "title": "cpu time - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "mergor_process_cpu_total{job=\"mergor\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "archives_created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mergor_archives_created_total" }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mergor_process_memory{job=\"mergor\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "cpu time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mergor_process_cpu{job=\"mergor\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "save time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(mergor_save_local_ms_total{job=\"mergor\"}[5m])",
     "legendFormat": "save_local"
    },
    {
     "expr": "irate(mergor_save_s3_ms_total{job=\"mergor\"}[5m])",
     "legendFormat": "save_s3"
    }
   ]
  }
 ]
}